language: python
python:
  - '3.5'

branches:
  only:
    - staging
 
before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=disquaire_projet2.settings.travis

script:
  - ./manage.py test
